# https://alacritty.org/config-alacritty.html

[window]
padding.x = 10
padding.y = 10

[general]
import = [
  "~/.config/alacritty/theme.toml",
  "~/.config/alacritty/font-size.toml",
  "~/.config/alacritty/fonts/JetBrainsMono.toml",
  "~/.config/alacritty/shared.toml",
]

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"
